[package]
name = "pocket_robot_guard"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.30.1"
pyth-solana-receiver-sdk = "0.1.0"
solana-program = "1.18"

[lib]
crate-type = ["cdylib", "lib"]
