[package]
name = "aegis_bot"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "aegis_bot"
path = "bot.rs" 

[dependencies]
tokio = { version = "1", features = ["full"] }
rust_ti = "0.1"
colored = "2.0"
