[dependencies]
tokio = { version = "1", features = ["full"] }
binary_options_tools = "0.1.9" # High-performance PocketOption Wrapper
vader-sentimental = "0.1.2"
ta = "0.5.0"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
